Recipe and Inventory Management System
marvin-nyalik/RecipeApp pull request #25
Opened 2023-10-12 15:04 UTC by Zafron047

## Dear Reviewer,
Please review the implementations of this project **Recipe App**. Please provide feedback or approve to merge to the `main` branch.

**Project Requirements:**

- [x] **Design:**
    - Implemented the layout based on the wireframes provided.
    - Personalized the design including colors, typographies, spacings, etc.
    - Designed using Tailwind CSS for a responsive and visually appealing UI.

- [x] **Authentication:**
    - Created login and registration pages using Devise for user authentication.

- [x] **Recipe Management:**
    - Developed pages for managing recipes, including:
        - Displaying a list of recipes created by the logged-in user and allowing navigation to recipe details.
        - Allowing users to delete recipes they own.
        - Displaying a list of public recipes ordered by newest and linking to recipe details.

- [x] **Recipe Details:**
    - Enabled a toggle button for users to switch recipes between public and private.
    - Displayed recipe details for public recipes or recipes owned by the user.
    - Provided a form for users to add new food to recipes they own.

- [x] **Inventory Management:**
    - Implemented inventory management pages, including:
        - Displaying a list of inventories created by the logged-in user and allowing navigation to inventory details.
        - Allowing users to delete inventories they own.

- [x] **Inventory Details:**
    - Displayed inventory details as per the wireframe.
    - Provided a form for users to add new food to their inventories.

- [x] **Recipe Details - Shopping List:**
    - Added a modal to select an inventory for creating a shopping list.

- [x] **Inventory Shopping List:**
    - Calculated the missing food items by comparing the recipe's food with the inventory.
    - Displayed the total count and price of missing food items.

- [x] **Performance:**
    - Ensured no N+1 queries are happening for efficient data retrieval.

- [x] **Navigation:**
    - Created a navigation menu for easy access to all project pages.

- [x] **Technical Setup:**
    - Established the repository on GitHub using Gitflow.
    - Configured Devise for user authentication.

- [x] **Testing:**
    - Set up RSpec and Capybara for unit and integration testing.

**UX and tests Video Clip:**

https://github.com/marvin-nyalik/RecipeApp/assets/117600135/a9df4f5f-4954-4bed-842d-9961c0dc38c0

### **Deploy Server:**

```
web: bin/rails server -p 3000
css: bin/rails tailwindcss:watch
```

**Files Added/Modified:**
- Created new pages and templates.
- Added controller actions and views.
- Updated routes for recipe, inventory, and shopping list functionalities.
- Created unit and integration tests for thorough coverage.

This pull request is ready for review and merging into the main codebase.

Thank you for your time and attention to this pull request!

## Regards,

@marvin-nyalik @Zafron047 @AnsarIbrahim

2023-10-12 17:15 UTC, Gambit142 requested changes
Hi @Zafron047 @marvin-nyalik @AnsarIbrahim 👋, 

Good job so far!

## Highlights
- Setup linters correctly ✔️ 
- Good use of Gitflow ✔️ 
- Use of `devise` for authentication ✔️ 
- Use of `Rspec` as testing library ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-10-12 17:15 UTC, Gambit142 commented on app/models/food.rb
> +end
- [ ] Based on the [schema diagram](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_erd.png) provided, the `Food` model and the `Recipe` model have a **_many-to-many relationship_**. Therefore, you need to set up the model properly. One way to achieve this is to use Ruby on Rails **_[has many :through](https://guides.rubyonrails.org/association_basics.html#:~:text=2.4%20The%20has_many%20%3Athrough%20Association) association_** between models. Kindly implement this change. 👍 💻

2023-10-12 17:15 UTC, Gambit142 commented on app/models/recipe.rb
> +end
- [ ] Based on the [schema diagram](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_erd.png) provided, the `Food` model and the `Recipe` model have a **_many-to-many relationship_**. Therefore, you need to set up the model properly. One way to achieve this is to use Ruby on Rails **_[has many :through](https://guides.rubyonrails.org/association_basics.html#:~:text=2.4%20The%20has_many%20%3Athrough%20Association) association_** between models. Kindly implement this change. 👍 💻

2023-10-12 17:15 UTC, Gambit142 commented on app/controllers/foods_controller.rb
> +end
- [ ] One of the major requirements for this project is to create an _**index**_ page for the **_food list_** that matches the wireframe below:

![image](https://github.com/marvin-nyalik/RecipeApp/assets/77106962/a471f688-4a92-41de-a505-a1300cc766de)

---

Kindly create the index page and ensure that it is accessible through the navigation bar. Also, kindly ensure that a user can delete the food item from the list. 👍 🖱️

2023-10-12 17:15 UTC, Gambit142 commented on app/views/recipes/index.html.erb
> +  </div>
- [ ] One of the requirements for this project is to ensure that only a user who creates a recipe should be able to delete it. For this purpose, I would advise you to use the `Cancancan` gem to control this. This is useful because you have a public recipe page that all users can view, therefore, it is a good security feature that only the user who created the recipe should be able to delete it. 👍 🖱️ 

---

Also, if I input the URL to display the `Recipes#Show` page for a recipe that another user created, the recipe will be displayed to the user. I also noticed that the user will be able to make other recipes created by other users public. This is another reason why I would advise you to use `Cancancan` to control what users can do in this application. 😎 💻

2023-10-12 17:15 UTC, Gambit142 commented on app/views/recipes/show.html.erb
> +          <% end %>
- [ ] Based on the requirement, the _**Add Ingredient**_ button should be shown if the person is the one who created the recipe. In a real-life setting, if you have a recipe, only the chef or the owner of the recipe should be the ones to determine ingredients that can be added to the recipe. Kindly use `Cancancan` to achieve this feature. 👍 💻

2023-10-12 17:37 UTC, marvin-nyalik commented on app/controllers/foods_controller.rb
> +end
This is not a requirement for a project of 3, you should be keen when requesting changes @Gambit142

2023-10-12 18:00 UTC, Gambit142 commented on app/controllers/foods_controller.rb
> +end
@marvin-nyalik, Kindly note that it is a requirement for this project regardless of the number of people in the team. 👍

![image](https://github.com/marvin-nyalik/RecipeApp/assets/77106962/80bf3dd1-9f89-40af-841e-9c498a9f9274)

Kindly check the third bullet point. 😎

2023-10-12 19:32 UTC, Zafron047 commented on app/controllers/foods_controller.rb
> +end
Dear @Gambit142 
I can understand that reviewing is a very hard job to do. Read line by line and see if we have left any bugs or errors and we do appreciate it very much.

Thank you for your kind effort however when we built the project we have followed the requirements given as per the project requirements: [Project requirement link](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md)

I am leaving a screenshot for your reference.
![food_index](https://github.com/marvin-nyalik/RecipeApp/assets/117600135/77607128-c536-4b32-bf97-f852effde213)


The food list page is a requirement for only the teams who are less than 3 in numbers.

Anyways, It is really common to do a tiny mistake not checking how many members we are and which requirements applied for a project and not. It is very normal.

And we thank you very much that you are helping us to make our project flaw free. I am marking this issue as resolved.

Best regards from all of us may you have a great day.

Best,

@Zafron047 @marvin-nyalik @AnsarIbrahim

2023-10-12 19:55 UTC, Zafron047 commented on app/models/food.rb
> +end
Thanks a lot for the sight. We somehow missed it. 🥲 Thanks for catching the bug and we have made the changes. 👍 Cheers.

2023-10-12 19:55 UTC, Zafron047 commented on app/models/recipe.rb
> +end
Thanks a lot for the sight. We somehow missed it. 🥲 Thanks for catching the bug and we have made the changes. 👍 Cheers.

2023-10-12 19:55 UTC, Zafron047 commented on app/views/recipes/index.html.erb
> +  </div>
Thanks for the good advice. We have the cancancan now and we have applied the authorization as per your required changes. 😃 👍

2023-10-12 19:55 UTC, Zafron047 commented on app/views/recipes/show.html.erb
> +          <% end %>
Thanks for the good advice. We have the cancancan now and we have applied the authorization as per your required changes. 😃 👍 

Thanks again for the review.

2023-10-12 19:57 UTC, Zafron047 commented
@Gambit142 Thanks a lot for the hardwork reviewing our project.

Have a great day . 😃 👍

2023-10-12 21:06 UTC, topeogunleye approved these changes
### Hi @Zafron047 @marvin-nyalik @AnsarIbrahim,

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
---

Hello @studentgroup! 🌟

I've reviewed the updates made in response to the previous feedback, and here's the breakdown of your progress:

### Model Relationship Adjustments: 🛠️
- Fantastic job in implementing the many-to-many relationship between the `Food` and `Recipe` models using the `has_many :through` association. This ensures accurate data representation and allows for a more intuitive interaction between these models. Kudos for addressing this crucial feedback! 👏🎯

### Authorization with Cancancan: 🔒
- You've brilliantly integrated the Cancancan gem to handle authorizations. It's great to see that only users who create a recipe now have the privilege to delete it. This implementation not only satisfies project requirements but also enhances the security and user experience of your application. Well done! 💪
  
- Additionally, implementing the Cancancan gem to display the "Add Ingredient" button only to the recipe creator aligns with real-world scenarios where only the chef or recipe owner determines the ingredients. This adds authenticity to your project and ensures the user experience is intuitive. Stellar work! 🍽️

### Overall: 🏆
Your attention to detail and commitment to refining your code based on feedback is genuinely commendable. The changes made ensure that your application aligns closely with real-world expectations, making it more user-friendly and secure.

Keep up the excellent work and always embrace continuous learning. Feedback is a stepping stone to greater achievements!

Should you have any questions, concerns, or seek further clarifications, feel free to reach out.

Warm regards and happy coding! 🚀👩‍💻
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 21:18 UTC, Gambit142 commented on app/controllers/foods_controller.rb
> +end
Hi @Zafron047, it was no mistake. Look at your [sneak peek](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md), it clearly states that you should create a `Foods#Index` page regardless of the number of team members.

---

The only pages that are dependent on the number of teams are:

- `Inventories#Index` page
- `Inventories#Show` page
- Popup on the `Recipes#Show` page to include inventories when adding an ingredient t the recipe and
- Inventories shopping list

Kindly refer to the requirements there. Thank you.

![image](https://github.com/marvin-nyalik/RecipeApp/assets/77106962/c251e6bc-c7a1-4455-aee6-024610256e83)

2023-10-12 21:26 UTC, Zafron047 commented
### Dear @topeogunleye 

Your encouraging words regarding the "Add Ingredient" button implementation for the recipe creator bring me a sense of accomplishment. I aimed to make the user experience as intuitive and realistic as possible, and your feedback validates that effort.

I'm genuinely grateful for your overall assessment and commendation of my attention to detail and commitment to improvement. Your words inspire us to continue striving for excellence and embracing feedback as a means to enhance my skills.

Thank you for your time, guidance, and support. Should you have any further suggestions, questions, or concerns, please do not hesitate to reach out. Your insights are invaluable to me.

## Dear @Gambit142 ,

I want to express my sincere gratitude for your thorough and constructive review. Your feedback has been incredibly valuable in helping me make significant improvements to the project. Your breakdown of the progress made my understanding of your comments clear and actionable.

I'm delighted that you found the implementation of the many-to-many relationship between the Food and Recipe models using the `has_many :through` association to be a fantastic job. It was indeed an important aspect of the project, and your recognition means a lot to me. I'm committed to ensuring accurate data representation and enhancing the interaction between these models.

Your positive feedback on the integration of the Cancancan gem for authorization is greatly appreciated. I'm pleased to hear that it aligns with both project requirements and the overall user experience. It's motivating to know that my efforts to enhance security and authenticity in the application have been successful.

Warm regards,

@Zafron047 , @marvin-nyalik , @AnsarIbrahim

2023-10-13 06:04 UTC, topeogunleye commented
> ### Dear @topeogunleye
> Your encouraging words regarding the "Add Ingredient" button implementation for the recipe creator bring me a sense of accomplishment. I aimed to make the user experience as intuitive and realistic as possible, and your feedback validates that effort.
> 
> I'm genuinely grateful for your overall assessment and commendation of my attention to detail and commitment to improvement. Your words inspire us to continue striving for excellence and embracing feedback as a means to enhance my skills.
> 
> Thank you for your time, guidance, and support. Should you have any further suggestions, questions, or concerns, please do not hesitate to reach out. Your insights are invaluable to me.
> 
> ## Dear @Gambit142 ,
> I want to express my sincere gratitude for your thorough and constructive review. Your feedback has been incredibly valuable in helping me make significant improvements to the project. Your breakdown of the progress made my understanding of your comments clear and actionable.
> 
> I'm delighted that you found the implementation of the many-to-many relationship between the Food and Recipe models using the `has_many :through` association to be a fantastic job. It was indeed an important aspect of the project, and your recognition means a lot to me. I'm committed to ensuring accurate data representation and enhancing the interaction between these models.
> 
> Your positive feedback on the integration of the Cancancan gem for authorization is greatly appreciated. I'm pleased to hear that it aligns with both project requirements and the overall user experience. It's motivating to know that my efforts to enhance security and authenticity in the application have been successful.
> 
> Warm regards,
> 
> @Zafron047 , @marvin-nyalik , @AnsarIbrahim

2023-10-13 06:33 UTC, topeogunleye commented
> ### Dear @topeogunleye
> Your encouraging words regarding the "Add Ingredient" button implementation for the recipe creator bring me a sense of accomplishment. I aimed to make the user experience as intuitive and realistic as possible, and your feedback validates that effort.
> 
> I'm genuinely grateful for your overall assessment and commendation of my attention to detail and commitment to improvement. Your words inspire us to continue striving for excellence and embracing feedback as a means to enhance my skills.
> 
> Thank you for your time, guidance, and support. Should you have any further suggestions, questions, or concerns, please do not hesitate to reach out. Your insights are invaluable to me.
> 
> ## Dear @Gambit142 ,
> I want to express my sincere gratitude for your thorough and constructive review. Your feedback has been incredibly valuable in helping me make significant improvements to the project. Your breakdown of the progress made my understanding of your comments clear and actionable.
> 
> I'm delighted that you found the implementation of the many-to-many relationship between the Food and Recipe models using the `has_many :through` association to be a fantastic job. It was indeed an important aspect of the project, and your recognition means a lot to me. I'm committed to ensuring accurate data representation and enhancing the interaction between these models.
> 
> Your positive feedback on the integration of the Cancancan gem for authorization is greatly appreciated. I'm pleased to hear that it aligns with both project requirements and the overall user experience. It's motivating to know that my efforts to enhance security and authenticity in the application have been successful.
> 
> Warm regards,
> 
> @Zafron047 , @marvin-nyalik , @AnsarIbrahim

@Zafron047, I am having a discussion with my senior colleagues and unfortunately, I may have to inform you that my approval was an error. please can you kindly implement the Food page?.

2023-11-08 07:06 UTC, merged